using System.Collections.Generic;
using UnityEngine;

namespace Sandplay.Core
{
    // Keep existing numeric values: saved language preferences use these IDs.
    public enum Language { English = 0, Chinese = 1, Spanish = 2, PortugueseBrazil = 3, French = 4, German = 5, Japanese = 6, Czech = 7 }

    public static partial class Localization
    {
        private static Language _current = Language.English;
        private static bool _initialized;
        public static Language Current { get { if (!_initialized) AutoDetect(); return _current; } }

        public static event System.Action OnLanguageChanged;

        /// <summary>
        /// Auto-detect device language on first access. Call early or let it self-init.
        /// Respects a previously saved user preference stored in PlayerPrefs.
        /// </summary>
        public static void AutoDetect()
        {
            if (_initialized) return;
            _initialized = true;

            // Restore saved preference first
            int saved = UnityEngine.PlayerPrefs.GetInt("sandplay_lang", -1);
            if (System.Enum.IsDefined(typeof(Language), saved))
            {
                _current = (Language)saved;
                return;
            }

            // No saved preference — fall back to system language
            _current = FromSystemLanguage(UnityEngine.Application.systemLanguage);
        }

        public static void SetLanguage(Language lang)
        {
            if (!System.Enum.IsDefined(typeof(Language), lang)) return;
            _initialized = true;
            if (_current == lang) return;
            _current = lang;
            UnityEngine.PlayerPrefs.SetInt("sandplay_lang", (int)lang);
            UnityEngine.PlayerPrefs.Save();
            OnLanguageChanged?.Invoke();
        }

        public static string Get(string key)
        {
            if (!_initialized) AutoDetect();
            if (TryGetAccessTranslation(key, out var accessText)) return accessText;
            if (TryGetSupportTranslation(key, out var supportText)) return supportText;
            if (TryGetReportTranslation(key, out var reportText)) return reportText;
            if (TryGetTherapistTranslation(key, out var therapistText)) return therapistText;
            var table = Table(_current);
            if (table.TryGetValue(key, out string val)) return val;
            // Fallback to English
            if (_en.TryGetValue(key, out string fallback)) return fallback;
            return key;
        }

        public static string Get(string key, params object[] args)
        {
            return string.Format(Culture, Get(key), args);
        }

        // ─── English ───────────────────────────────────────
        private static readonly Dictionary<string, string> _en = new Dictionary<string, string>
        {
            ["records.local"] = "Local import & recovery",
            // Toolbar
            ["toolbar.sand"] = "Sand",
            ["tool.raise"] = "Raise",
            ["tool.dig"] = "Dig",
            ["tool.smooth"] = "Smooth",
            ["tool.flatten"] = "Flat",
            ["tool.walk"] = "Walk",
            ["tool.settings"] = "Settings",
            ["tool.ai_analysis"] = "AI\nReflection",
            ["tool.manual_analysis"] = "Manual\nReport",
            ["tool.exit"] = "Exit",
            ["tool.sand_material"] = "Texture",

            // Sand material presets
            ["mat.sand"] = "Sand",
            ["mat.rock"] = "Rock",
            ["mat.grass"] = "Grass",
            ["mat.snow"] = "Snow",
            ["mat.mud"] = "Mud",
            ["mat.water"] = "Water",
            ["mat.clay"] = "Clay",

            // Manual report panel
            ["manual.title"] = "Manual Report",
            ["manual.placeholder"] = "Type your observations, notes, or session summary here\u2026",
            ["manual.save"] = "Save Report",
            ["manual.saved"] = "Report saved!",
            ["manual.empty"] = "Please write something before saving.",

            // Subscription / paywall
            ["sub.pro_badge"] = "PRO",
            ["sub.subscribed_badge"] = "PRO+",
            ["sub.vip_feature"] = "Unlock this feature",
            ["sub.upgrade"] = "Upgrade to PRO",
            ["sub.paywall_title"] = "Sandtray Pro",
            ["sub.paywall_subtitle"] = "Host, connect, create, and reflect together.",
            ["sub.paywall_free_note"] = "Free: 3 hosted sessions total; 3 AI reflections and 3 PDF exports per month.",
            ["sub.feature_ai"] = "Unlimited AI Reflections",
            ["sub.feature_host"] = "Unlimited Session Hosting",
            ["sub.feature_calls"] = "Video & voice calls in sessions",
            ["sub.feature_reports"] = "Unlimited PDF Reports",
            ["sub.feature_replays"] = "Full Replay History",
            ["sub.feature_support"] = "Priority Support",
            ["sub.loading"] = "Loading plans…",
            ["sub.subscribe"] = "Subscribe",
            ["sub.restore"] = "Restore Purchases",
            ["sub.restoring"] = "Restoring…",
            ["sub.restored_yes"] = "Subscription restored!",
            ["sub.restored_no"] = "No active subscription found.",
            ["sub.purchasing"] = "Processing…",
            ["sub.purchase_ok"] = "Welcome to Sandtray Pro!",
            ["sub.purchase_err"] = "Purchase failed: {0}",
            ["sub.terms"] = "Subscriptions auto-renew unless cancelled 24h before renewal.",
            ["sub.privacy"] = "Privacy Policy",
            ["sub.terms_link"] = "Terms of Use",
            ["sub.best_value"] = "Best value",
            ["sub.save_percent"] = "Save {0}%",
            ["sub.locked_ai"] = "AI-assisted reflection is a Pro feature. Subscribe to unlock.",
            ["sub.locked_host"] = "Sign in to host a session. Free accounts get 3 hosted sessions.",
            ["sub.free_ai_limit"] = "You have used your 3 free AI reflections this month. Upgrade to VIP for unlimited reflections.",
            ["sub.free_pdf_limit"] = "You have used your 3 free PDF exports this month. Upgrade to VIP for unlimited exports.",
            ["sub.free_host_limit"] = "You have used your 3 free hosted sessions. Upgrade to VIP for unlimited hosting.",
            ["sub.locked_replay"] = "Free accounts can play the latest replay. Upgrade to VIP to unlock all older replays.",
            ["sub.period_month"] = "/ month",
            ["sub.period_year"] = "/ year",
            ["sub.period_week"] = "/ week",
            ["sub.period_once"] = "once",
            ["sub.no_plans"] = "No plans available.",
            ["sub.mobile_only"] = "Subscriptions are available on iOS and Android.\nPlease subscribe from the mobile app.",
            ["sub.ok"] = "OK",

            // Brush
            ["brush.radius"] = "Radius",
            ["brush.strength"] = "Strength",
            ["brush.radius_val"] = "R:{0:F1}",
            ["brush.strength_val"] = "S:{0:F1}",

            // Catalog
            ["catalog.title"] = "Object Catalog",
            ["button.catalog"] = "Catalog",

            // Status
            ["status.ready"] = "Ready",
            ["status.hint"] = "Ready - Right-click to orbit, Scroll to zoom, Middle-click to pan",
            ["status.selected"] = "Selected: {0}",
            ["status.selected_many"] = "{0} objects selected · Drag any selected object to move the group",
            ["selection.count"] = "{0} selected",
            ["selection.hint"] = "Drag empty sand to box-select · Shift-click to add/remove",
            ["status.saved"] = "Saved: {0}",
            ["status.autosaved_now"] = "Auto-saved just now",
            ["status.autosaved_ago"] = "Auto-saved {0} ago",
            ["status.will_save_in"] = "Will save in {0}",
            ["status.one_second"] = "{0} second",
            ["status.seconds"] = "{0} seconds",
            ["status.one_minute"] = "{0} minute",
            ["status.minutes"] = "{0} minutes",
            ["save.title"] = "Board saving",
            ["save.local"] = "Saved on this device · autosave on",
            ["quota.pending"] = "Quota check pending",
            ["quota.confirmed"] = "Quota confirmed",
            ["quota.full"] = "Capacity reached · local work can continue",
            ["quota.signin"] = "Sign in to check quota · local work can continue",
            ["quota.offline"] = "Quota check unavailable · will retry",
            ["quota.recovery"] = "Quota needs attention · local files preserved",
            ["quota.none"] = "No local quota registration required",
            ["quota.legacy"] = "Existing local board",
            ["quota.retry"] = "Tap to retry quota check",
            ["backup.none"] = "Not backed up to cloud",
            ["backup.unknown"] = "Cloud backup status unknown",
            ["backup.uploading"] = "Uploading backup…",
            ["backup.saved"] = "Saved version backed up",
            ["backup.changed"] = "Saved changes not backed up",
            ["backup.failed"] = "Backup incomplete · local file preserved",
            ["social.google"] = "Sign in with Google",
            ["social.apple"] = "Sign in with Apple",
            ["social.continue_google"] = "Continue with Google",
            ["social.continue_apple"] = "Continue with Apple",
            ["social.open"] = "Open sign-in in browser",
            ["social.preparing"] = "Preparing sign-in…",
            ["social.waiting"] = "Continue in your browser. If it didn’t open, use the button below.",
            ["social.unavailable"] = "Social sign-in is not configured or is temporarily unavailable. Email sign-in is still available.",
            ["social.existing"] = "An account already uses this email. Sign in with your existing method; automatic account linking is not enabled.",
            ["social.expired"] = "Sign-in expired. Please try again.",
            ["social.cancelled"] = "Sign-in cancelled. You can try again.",
            ["social.failed"] = "Sign-in could not be completed. Please try again.",
            ["save.automatic"] = "Autosave on · every 30 seconds",
            ["save.host_managed"] = "Saving is managed by the host · no local copy",
            ["save.inactive"] = "Autosave is not active",
            ["save.saved"] = "All board changes saved on this device",
            ["save.recovered"] = "Recovered the previous saved copy of this board",
            ["save.failed"] = "Could not save. Keep this board open, check available storage, and try again.",
            ["save.load_failed"] = "This board could not be opened. Its saved files have been retained.",
            ["save.create_failed"] = "The new board could not be saved. Please try again. If the problem continues, check Local save recovery in Settings.",
            ["status.loaded"] = "Loaded: {0}",
            ["status.object"] = "Object",

            // Action panel fallbacks
            ["action.vertical"] = "\u2195",
            ["action.rotate"] = "\u21BB",
            ["action.resize"] = "\u2922",
            ["action.duplicate"] = "Duplicate",
            ["action.delete"] = "\u2716",

            // Analysis
            ["analysis.title"] = "AI-Assisted Reflection",
            ["analysis.ask"] = "Create AI Reflection",
            ["analysis.loading"] = "Preparing reflection... Please wait...",
            ["analysis.login_required"] = "Create a free account or sign in to use AI-assisted reflection.",
            ["analysis.disclaimer"] = "AI-assisted reflection — not a diagnosis or clinical conclusion. Observations and optional hypotheses are separated below; only the creator can confirm personal meaning.",
            ["analysis.error.capture"] = "Failed to capture session data.",
            ["analysis.error.manager"] = "AIAnalysisManager not found in scene.",
            ["analysis.error"] = "Error: {0}",
            ["analysis.save"] = "Save",
            ["analysis.saved"] = "Saved",
            ["analysis.export_pdf"] = "Export PDF",
            ["analysis.save_not_logged_in"] = "Not logged in",
            ["analysis.saving"] = "Saving to cloud...",
            ["analysis.save_done"] = "Saved to cloud",
            ["analysis.auto_saved"] = "Saved automatically · cloud backup queued",
            ["analysis.auto_save_button"] = "Auto-saved",
            ["analysis.save_fail"] = "Save failed: {0}",
            ["analysis.pdf_login_required"] = "Login required for PDF",
            ["analysis.wait_save"] = "Please wait...",
            ["analysis.pdf_generating"] = "Generating PDF...",
            ["analysis.pdf_saved"] = "PDF saved: {0}",
            ["analysis.pdf_fail"] = "PDF error: {0}",

            // Walk mode
            ["walk.exit"] = "Exit Walk",

            // Main menu
            ["menu.title"] = "Sandtray",
            ["menu.subtitle"] = "THERAPEUTIC WORKSPACE",
            ["menu.welcome"] = "Welcome back, {0}",
            ["menu.welcome_guest"] = "Welcome",
            ["menu.welcome_sub"] = "Create, explore and reflect in your sandtray world.",
            ["menu.workspace"] = "YOUR WORKSPACE",
            ["menu.workspace_heading"] = "A space to create and reflect",
            ["menu.workspace_sub"] = "Start a new sandtray or continue where you left off.",
            ["menu.continue_playing"] = "My boards",
            ["menu.view_all"] = "View All  >",
            ["menu.nav_home"] = "Home",
            ["menu.nav_boards"] = "My Boards",
            ["menu.my_boards_sub"] = "{0} boards · Your spaces to create and reflect.",
            ["menu.my_boards_open"] = "Open",
            ["menu.search_boards"] = "Search boards",
            ["menu.filter_all"] = "All boards",
            ["menu.filter_client"] = "Client boards",
            ["menu.sort_updated"] = "Last updated",
            ["menu.sort_name"] = "Name A–Z",
            ["menu.sort_oldest"] = "Oldest updated",
            ["menu.table_board"] = "Board",
            ["menu.table_client"] = "Client",
            ["menu.table_updated"] = "Last updated",
            ["menu.table_actions"] = "Actions",
            ["menu.range"] = "Showing {0}–{1} of {2} boards",
            ["menu.range_empty"] = "Showing 0 boards",
            ["menu.nav_multiplayer"] = "Multiplayer",
            ["menu.nav_replays"] = "Replays",
            ["menu.nav_ai"] = "AI Reflection",
            ["menu.nav_objects"] = "Objects",
            ["menu.nav_settings"] = "Settings",
            ["menu.cta_new_desc"] = "Create a new sandtray world.",
            ["menu.cta_host_desc"] = "Create and invite others to join.",
            ["menu.cta_join_desc"] = "Join a friend's ongoing session.",
            ["menu.tile_replays"] = "Replays",
            ["menu.tile_replays_desc"] = "Watch and reflect on your past sessions.",
            ["menu.tile_ai"] = "AI-Assisted Reflection",
            ["menu.tile_ai_desc"] = "Explore observations, possibilities, and open questions.",
            ["menu.tile_objects"] = "Objects Library",
            ["menu.tile_objects_desc"] = "Unlock all objects and build your world.",
            ["menu.tile_multiplayer"] = "Multiplayer",
            ["menu.tile_multiplayer_desc"] = "Create or join real-time sessions.",
            ["menu.new_board"] = "New Board",
            ["menu.host_online"] = "Host Online",
            ["menu.join_session"] = "Join Session",
            ["menu.saved_boards"] = "Saved Boards",
            ["menu.empty"] = "Begin with a blank sandtray, or join a live session with a room code.",
            ["menu.empty_title"] = "Create your first board",
            ["menu.empty_action"] = "Create a board",
            ["menu.empty_join"] = "Join with a room code",
            ["menu.no_results_title"] = "No boards match your filters",
            ["menu.no_results"] = "Try another search or show all of your boards.",
            ["menu.clear_filters"] = "Clear filters",
            ["menu.account"] = "Account",
            ["menu.replays"] = "Replays",
            ["replays.title"] = "Session Replays",
            ["replays.empty"] = "No recorded sessions yet.",
            ["replays.duration"] = "{0}s, {1} events",
            ["replays.play"] = "Play",
            ["replays.vip_locked"] = "VIP",
            ["replays.upgrade"] = "Upgrade",
            ["replays.delete"] = "Delete",
            ["replays.close"] = "Close",
            ["replays.confirm_delete"] = "Delete this replay?",
            ["replays.read_only"] = "READ-ONLY REPLAY",
            ["replays.stop"] = "Stop",
            ["replays.quit"] = "Quit",
            ["replays.pause"] = "Pause",
            ["replays.resume"] = "Play",
            ["replays.finished"] = "Replay finished",
            ["replays.replay_again"] = "Replay again",
            ["replays.back_list"] = "Back to list",
            ["replays.free_note"] = "Free: only the latest replay is playable. Upgrade for full history.",
            ["replays.storage_note"] = "Replays are stored on this device. Delete old ones to free space.",
            ["replays.latest_badge"] = "Latest",
            ["replays.reset_view"] = "Reset view",
            ["replays.export_video"] = "Export",
            ["replays.exporting"] = "Exporting video… {0}%",
            ["replays.export_done"] = "Video ready to share",
            ["replays.export_fail"] = "Export failed: {0}",
            ["replays.export_too_long"] = "Replay is too long to export (max 5 min).",

            // Login / Account
            ["login.title"] = "Sign In",
            ["login.email"] = "Email",
            ["login.welcome_back"] = "Welcome back",
            ["login.create_heading"] = "Create your account",
            ["login.email_address"] = "Email address",
            ["login.email_placeholder"] = "you@example.com",
            ["login.password_placeholder"] = "Enter your password",
            ["login.name_placeholder"] = "Enter your full name",
            ["login.or"] = "or",
            ["login.have_account"] = "Already have an account?",
            ["login.create_account"] = "Create account",
            ["login.forgot_password"] = "Forgot password?",
            ["login.password"] = "Password",
            ["login.sign_in"] = "Sign In",
            ["login.register"] = "Create Account",
            ["login.signing_in"] = "Signing in...",
            ["login.registering"] = "Creating account...",
            ["login.success"] = "Welcome, {0}",
            ["login.error"] = "Error: {0}",
            ["login.logged_in_as"] = "Signed in as {0}",
            ["login.sign_out"] = "Sign Out",
            ["login.name"] = "Full Name",
            ["login.user_type"] = "Account type",
            ["login.type_normal"] = "Personal",
            ["login.type_psychologist"] = "Therapist",
            ["login.type_organization"] = "Organization",

            // Board list
            ["board.open"] = "Open",
            ["board.rename"] = "Rename",
            ["board.reports"] = "Reports",
            ["board.delete"] = "Delete",
            ["board.loading"] = "Opening board…",
            ["board.loading_new"] = "Preparing board…",
            ["board.loading_catalog"] = "Loading catalog…",
            ["board.loading_prepare"] = "Setting up sandtray…",
            ["board.loading_restore"] = "Restoring board…",
            ["board.loading_objects"] = "Placing objects…",
            ["board.loading_ready"] = "Almost ready…",

            // Reports panel
            ["reports.title"] = "Reports: {0}",
            ["reports.empty"] = "No AI reflection reports yet.\nOpen this board and create an AI-assisted reflection.",
            ["reports.view"] = "View",
            ["reports.delete"] = "Delete",
            ["reports.pdf"] = "\uD83D\uDCC4 PDF",
            ["reports.detail_title"] = "Report \u2014 {0}",
            ["reports.pdf_login"] = "Login required for PDF",
            ["reports.pdf_uploading"] = "Uploading\u2026",
            ["reports.pdf_downloading"] = "Generating PDF\u2026",
            ["reports.pdf_saved"] = "PDF saved!",
            ["reports.pdf_error"] = "PDF error: {0}",

            // Dialogs
            ["dialog.new_board"] = "New Board",
            ["dialog.rename"] = "Rename Board",
            ["dialog.ok"] = "OK",
            ["dialog.cancel"] = "Cancel",
            ["exit.title"] = "Quit table?",
            ["exit.confirm"] = "Are you sure you want to leave this table and return to the main menu?",

            // Size dialog
            ["size.title"] = "Choose Board Size",
            ["size.standard"] = "Standard (Square)",
            ["size.standard_desc"] = "10 × 10",
            ["size.medium"] = "Medium (Wide)",
            ["size.medium_desc"] = "10 × 13",
            ["size.custom"] = "Custom",
            ["size.width"] = "W:",
            ["size.depth"] = "H:",

            // Host panel
            ["host.title"] = "Host Online Session",
            ["host.info"] = "Choose a hosting mode, then open a board.\nThe room will be created after you enter the board.",
            ["host.cloud"] = "\u2601  Cloud Session  (room code \u2014 works anywhere)",
            ["host.lan"] = "\u26A1  LAN Session  (same Wi-Fi \u2014 IP: {0})",
            ["host.cancel"] = "Cancel",

            // Join panel
            ["join.title"] = "Join Session",
            ["join.role_label"] = "Join as:",
            ["join.observer"] = "Observer",
            ["join.therapist"] = "Therapist",
            ["join.patient"] = "Patient",
            ["host.therapist_mode"] = "Therapist Mode",
            ["host.therapist_mode_desc"] = "Tap to switch. Participants observe until you approve editing in Manage.",
            ["host.client_edits"] = "Client edits · I host and observe",
            ["host.client_edits_desc"] = "The first client to join can edit automatically. You can change this in Manage.",
            ["net.connection_error_title"] = "Session connection failed",
            ["net.dismiss"] = "Close",
            ["clients.confirm_move"] = "Confirm move to {0}",
            ["reports.review_title"] = "Review before export",
            ["reports.edit"] = "Edit report",
            ["reports.revisions"] = "Previous versions",
            ["reports.revisions_notice"] = "Previous text, newest first. Dates show when text was replaced. This local history is not a verified audit trail.",
            ["reports.revisions_empty"] = "No previous versions.",
            ["reports.edit_notice"] = "Changes are saved locally with previous text preserved. Edited reports require a new PDF export. AI text is not a diagnosis.",
            ["reports.edit_stale"] = "The report or account changed. Close and reopen this report before editing.",
            ["reports.review_notice"] = "Review the report for accuracy and sensitive information. AI text is not a diagnosis. Continuing sends this report to the server for PDF export.",
            ["reports.review_confirm"] = "I reviewed it · Export PDF",
            ["clients.history_no_matches"] = "No matching boards. Clear the search to see all records.",
            ["clients.history"] = "Assignment history",
            ["clients.history_unassigned"] = "Unassigned",
            ["clients.history_missing"] = "Missing client ({0})",
            ["clients.history_local"] = "Local device history, not a verified audit log. Client names reflect current records.",
            ["clients.history_change"] = "From: {0}\nTo: {1}",
            ["clients.history_unknown_date"] = "Unknown date",
            ["clients.history_empty"] = "No recorded assignment changes.",
            ["clients.search_tables"] = "Search boards by name…",
            ["clients.recovered"] = "Client records restored from a local backup. Recent changes may be missing; please review.",
            ["clients.search_reports"] = "Search board names or report text…",
            ["session.paused"] = "Editing paused",
            ["session.paused_name"] = "Paused: {0}",
            ["session.waiting"] = "Waiting for an editor",
            ["session.editing_name"] = "Editing: {0}",
            ["session.you_edit"] = "You edit",
            ["session.observing"] = "Observing",
            ["session.manage"] = "Manage",
            ["session.resume"] = "Resume editing",
            ["session.pause"] = "Pause editing",
            ["session.take_control"] = "Let me edit",
            ["session.editing"] = "Editing",
            ["session.approve"] = "Approve editing",
            ["session.give_control"] = "Give control",
            ["session.decline"] = "Decline editing",
            ["session.remove"] = "Remove",
            ["session.confirm_remove"] = "Confirm removal",
            ["session.waiting_people"] = "Waiting for participants…",
            ["catalog.edit_permission_title"] = "Editing permission required",
            ["catalog.edit_permission_required"] = "You don't have permission to edit this board. Ask the host to enable editing.",
            ["catalog.host_edit_permission_required"] = "You are currently observing. Open Manage and choose “Let me edit” to use the catalog.",
            ["session.loading_title"] = "Loading session",
            ["session.loading_receiving"] = "Receiving session… 0%",
            ["session.loading_objects"] = "Loading objects… {0}/{1} ({2}%)",
            ["session.loading_success"] = "Session ready · 100%",
            ["session.loading_failed_title"] = "Unable to load session",
            ["session.loading_failed"] = "Some session objects could not be loaded.",
            ["session.loading_disconnected"] = "Connection ended before the session finished loading.",
            ["session.loading_return"] = "Return home",
            ["session.removed"] = "The host removed you from this session. Tap to dismiss.",
            ["net.update_required"] = "The app and session server are incompatible. Update the app. If it is current, contact support to update the server. Tap to dismiss.",
            ["host.i_edit"] = "I edit · Others observe",
            ["net.patient_active"] = "Patient connected",
            ["therapist.patient_acting"] = "Patient is sculpting…",
            ["therapist.patient_painting"] = "Patient is painting…",
            ["therapist.patient_placing"] = "Patient placed an object",
            ["join.cloud_label"] = "Join via Room Code",
            ["join.placeholder_code"] = "ABC123",
            ["join.scan_qr"] = "Scan QR",
            ["join.join_room"] = "Join Room",
            ["join.invalid_code"] = "Enter the room code (4-6 letters)",
            ["join.joining"] = "Joining...",
            ["join.room_not_found"] = "Room not found or connection failed",
            ["join.or"] = "or",
            ["join.lan_label"] = "\u26A1  Join via IP Address  (same Wi-Fi)",
            ["join.placeholder_ip"] = "192.168.1.",
            ["join.connect"] = "Connect",
            ["join.missing_ip"] = "Please enter an IP address",
            ["join.connecting"] = "Connecting...",
            ["join.connection_failed"] = "Connection failed",
            ["join.cancel"] = "Cancel",

            // Network
            ["net.room"] = "Room: {0}",
            ["net.connecting"] = "Connecting...",
            ["net.spectating"] = "SPECTATING",
            ["net.viewers"] = "{0} viewer{1}",
            ["net.viewers_s"] = "s",

            // Reconnect
            ["reconnect.return"] = "Return to Menu",
            ["reconnect.message"] = "Connection lost\nReconnecting... ({0}/10)",

            // Client organization (local, alongside saved tables)
            ["clients.title"] = "Clients",
            ["clients.new"] = "+ New client",
            ["clients.local_note"] = "Client records, tables and reports are saved on this device. No cloud sync.",
            ["clients.local_archived"] = "Including archived clients · Saved on this device, not synced to the cloud.",
            ["clients.search"] = "Search name or client code…",
            ["clients.archived_toggle"] = "Show / hide archived",
            ["clients.archived"] = "Archived",
            ["clients.empty"] = "No matching clients. Create a client to start organizing their tables.",
            ["clients.unassigned"] = "Unassigned tables",
            ["clients.unassigned_help"] = "Your existing tables stay here until you move them into a client's record. Moving a table keeps all its reports.",
            ["clients.counts"] = "Tables: {0} · Reports: {1}",
            ["clients.report_count"] = "Reports: {0}",
            ["clients.edit"] = "Edit profile",
            ["clients.new_table"] = "+ New table",
            ["clients.archive"] = "Archive client",
            ["clients.restore"] = "Restore client",
            ["clients.tables"] = "Tables",
            ["clients.reports"] = "Reports",
            ["clients.view"] = "View",
            ["clients.open"] = "Open",
            ["clients.move"] = "Move",
            ["clients.move_title"] = "Move to client",
            ["clients.no_tables"] = "No tables yet. Create one for this client, or move an existing table from Unassigned tables or My Boards.",
            ["clients.no_reports"] = "No reports yet. Reports saved on this client's tables will appear here.",
            ["clients.name"] = "Name or alias *",
            ["clients.reference"] = "Client code",
            ["clients.dob"] = "Date of birth",
            ["clients.choose_date"] = "Select date…",
            ["clients.no_date"] = "No date selected · optional",
            ["clients.clear_date"] = "Clear",
            ["clients.done"] = "Done",
            ["clients.select"] = "Select",
            ["clients.choose_photo"] = "Choose photo",
            ["clients.remove_photo"] = "Remove",
            ["clients.photo_hint"] = "Optional profile photo · centre-cropped preview. Saved on this device.",
            ["clients.photo_error"] = "Couldn't open this photo. Check photo access or try a JPG/PNG under 20 MB.",
            ["clients.phone"] = "Phone",
            ["clients.email"] = "Email",
            ["clients.optional"] = "Only a name or alias is required. A client does not need an app account.",
            ["clients.notes"] = "Notes",
            ["clients.save"] = "Save client",
            ["clients.invalid_name"] = "Enter a name or alias (up to 100 characters).",
            ["clients.rename_error"] = "Could not rename this table. Choose a name that is not already in use.",
            ["clients.invalid_dob"] = "Use a valid birth date: YYYY-MM-DD, not in the future.",
            ["clients.invalid_account"] = "Select a valid account from search or friends.",
            ["clients.account_locked"] = "This client already has a linked account. The saved identity cannot be replaced here.",
            ["clients.duplicate_account"] = "This account is already linked to another client, including archived clients. Open the existing client record.",
            ["clients.duplicate_reference"] = "That client code is already in use. Choose another code or leave it blank.",
            ["clients.storage_error"] = "Could not read or save local records. Check device storage and try again.",

            // Settings
            ["settings.title"] = "Settings",
            ["settings.close"] = "\u00D7",
            ["settings.sand_color"] = "Sand Color",
            ["settings.box_outer"] = "Box Outer",
            ["settings.box_inner"] = "Box Inner",
            ["settings.floor"] = "Floor",
            ["settings.allow_objects_in_air"] = "Allow objects in air",
            ["settings.restore"] = "Restore Defaults",
            ["settings.pick"] = "Pick",
            ["shortcuts.title"] = "Keyboard Shortcuts",
            ["shortcuts.hint"] = "Click a keybinding to change it. Saved on this device. Shift makes object adjustments finer.",
            ["shortcuts.search"] = "Search actions or keys…",
            ["shortcuts.default"] = "Default",
            ["shortcuts.custom"] = "Customized",
            ["shortcuts.reset"] = "Reset",
            ["shortcuts.reset_all"] = "Reset all",
            ["shortcuts.reset_confirm"] = "Restore all default keyboard shortcuts? Your custom bindings will be removed.",
            ["shortcuts.press"] = "Press a key combination, then click Save. Escape cancels. A hardware keyboard is required.",
            ["shortcuts.fine"] = "Shift is reserved for fine adjustment with this action.",
            ["shortcuts.save"] = "Save",
            ["shortcuts.saved"] = "Shortcuts saved on this device.",
            ["shortcuts.unassign"] = "Unassign",
            ["shortcuts.reserved"] = "This key is reserved for navigation, camera controls, or the system. Choose another combination.",
            ["shortcuts.conflict"] = "Already used by {0}. Reassign or unassign that action first.",
            ["shortcuts.save_error"] = "Could not save shortcuts. Please try again.",
            ["shortcuts.empty"] = "No matching shortcuts.",
            ["shortcuts.action.Raise"] = "Raise object",
            ["shortcuts.action.Lower"] = "Lower object",
            ["shortcuts.action.RotateLeft"] = "Rotate left",
            ["shortcuts.action.RotateRight"] = "Rotate right",
            ["shortcuts.action.Enlarge"] = "Enlarge object",
            ["shortcuts.action.Shrink"] = "Shrink object",
            ["shortcuts.action.Duplicate"] = "Duplicate object",
            ["shortcuts.action.Delete"] = "Delete object",
            ["shortcuts.action.Copy"] = "Copy object",
            ["shortcuts.action.Paste"] = "Paste object",
            ["shortcuts.action.Undo"] = "Undo",
            ["shortcuts.action.Redo"] = "Redo",
            ["settings.language"] = "Language",
            ["settings.theme"] = "Appearance",
            ["settings.theme_light"] = "Light",
            ["settings.theme_dark"] = "Dark",
            ["board.client_label"] = "Client: {0}",
            ["board.client_linked"] = "Linked to client",
            ["settings.description"] = "Make Sandtray work the way you do.",
            ["settings.subscription"] = "Subscription",
            ["settings.view_plans"] = "View plans ›",
            ["settings.configure"] = "Customize ›",
            ["settings.view"] = "View ›",
            ["settings.sign_in"] = "Sign in",
            ["settings.managed"] = "Managed account",
            ["settings.off"] = "Off",
            ["settings.on"] = "On",
            ["settings.reset"] = "Reset",
            ["settings.custom_color"] = "Custom color…",
            ["credits.title"] = "Attributions",
            ["credits.subtitle"] = "With thanks to the creators of our 3D objects",
            ["credits.body"] = "Built-in 3D models include works by Poly by Google, sourced from Poly Pizza (poly.pizza).\nLicensed under Creative Commons Attribution 3.0 Unported (CC BY 3.0).",
            ["credits.changes"] = "Adaptations: models are imported into Unity and rescaled for Sandtray; materials and rendering may differ from the originals.",
            ["credits.disclaimer"] = "No sponsorship or endorsement by Google or Poly Pizza is implied. This credit does not cover user-uploaded objects.",
            ["credits.creator"] = "Creator profile",
            ["credits.source"] = "Poly Pizza",
            ["credits.models"] = "Model credits",
            ["account.type_title"] = "Account type",
            ["account.type_hint"] = "Switch how you use Sandtray. Your boards, client records and reports are kept. This does not change your subscription or verify professional credentials.",
            ["account.normal"] = "Personal",
            ["account.personal"] = "Personal",
            ["account.therapist"] = "Therapist",
            ["account.organization"] = "Organization",
            ["organization.nav"] = "Organization",
            ["account.current"] = "Current",
            ["account.sign_in"] = "Sign in using Account above to change your account type.",
            ["account.managed"] = "This account type is managed by an administrator.",
            ["account.saving"] = "Saving account type…",
            ["records.capacity_pending"] = "Saving report; waiting for capacity confirmation…",
            ["account.saved"] = "Account type saved.",
            ["account.failed"] = "Could not save. Check your connection and try again.",
            ["credits.license"] = "CC BY 3.0",

            // Color picker
            ["colorpicker.title"] = "Pick Color",
            ["colorpicker.done"] = "Done",

            // QR scanner
            ["qr.title"] = "Scan QR Code",
            ["qr.instruction"] = "Point camera at a room QR code",
            ["qr.cancel"] = "Cancel",
            ["qr.requesting"] = "Requesting camera permission...",
            ["qr.waiting"] = "Waiting for camera...",
            ["qr.scanning"] = "Scanning...",
            ["qr.found"] = "Found: {0}",
            ["qr.tap_close"] = "Tap anywhere to close",

            // HUD
            ["hud.radius"] = "Radius: {0:F1}",
            ["hud.strength"] = "Strength: {0:F1}",
            ["hud.select"] = "Select",
            ["hud.raise_sand"] = "Raise Sand",
            ["hud.dig_sand"] = "Dig Sand",
            ["hud.smooth_sand"] = "Smooth Sand",
            ["hud.flatten_sand"] = "Flatten Sand",
            ["hud.place_object"] = "Place Object",
            ["hud.move_object"] = "Move Object",
            ["hud.rotate_object"] = "Rotate Object",
            ["hud.scale_object"] = "Scale Object",
            ["hud.none"] = "None",
            ["hud.saved"] = "Session saved!",
            ["hud.loaded"] = "Session loaded!",
            ["hud.screenshot"] = "Screenshot saved!",
            ["hud.analysis"] = "Analysis requested...",

            // Agora voice / video
            ["agora.mic_on"] = "Mic On",
            ["agora.mic_off"] = "Mute",
            ["agora.cam_on"] = "Cam On",
            ["agora.cam_off"] = "Cam Off",
            ["agora.show"] = "Show",
            ["agora.hide"] = "Hide",
            ["agora.leave"] = "End Call",
            ["agora.connecting"] = "Connecting audio…",
            ["agora.comm_title"] = "Communication",
            ["agora.you"] = "You",
            ["cat.Animals"] = "Animals",
            ["cat.People"] = "People",
            ["cat.Buildings"] = "Buildings",
            ["cat.Nature"] = "Nature",
            ["cat.Vehicles"] = "Vehicles",
            ["cat.Abstract"] = "Abstract",
        };

        // ─── Chinese (Simplified) ──────────────────────────
        private static readonly Dictionary<string, string> _zh = new Dictionary<string, string>
        {
            ["records.local"] = "本地导入与恢复",
            // Toolbar
            ["toolbar.sand"] = "沙子",
            ["tool.raise"] = "堆高",
            ["tool.dig"] = "挖掘",
            ["tool.smooth"] = "平滑",
            ["tool.flatten"] = "压平",
            ["tool.walk"] = "行走",
            ["tool.settings"] = "设置",
            ["tool.ai_analysis"] = "AI\n反思",
            ["tool.manual_analysis"] = "手动\n报告",
            ["tool.exit"] = "退出",
            ["tool.sand_material"] = "材质",

            // Sand material presets
            ["mat.sand"] = "沙子",
            ["mat.rock"] = "岩石",
            ["mat.grass"] = "草地",
            ["mat.snow"] = "雪地",
            ["mat.mud"] = "泥土",
            ["mat.water"] = "水面",
            ["mat.clay"] = "黏土",

            // Manual report panel
            ["manual.title"] = "手动报告",
            ["manual.placeholder"] = "在此输入您的观察、笔记或会话总结…",
            ["manual.save"] = "保存报告",
            ["manual.saved"] = "报告已保存！",
            ["manual.empty"] = "请先写一些内容就能保存。",

            // Subscription / paywall
            ["sub.pro_badge"] = "PRO",
            ["sub.subscribed_badge"] = "PRO+",
            ["sub.vip_feature"] = "解锁此功能",
            ["sub.upgrade"] = "升级到专业版",
            ["sub.paywall_title"] = "Sandtray 专业版",
            ["sub.paywall_subtitle"] = "主持会话、连接彼此，共同创作与反思。",
            ["sub.paywall_free_note"] = "免费版：共可主持 3 次会话；每月 3 次 AI 反思和 3 份 PDF 导出。",
            ["sub.feature_ai"] = "无限 AI 辅助反思",
            ["sub.feature_host"] = "无限会话托管",
            ["sub.feature_calls"] = "会话内视频与语音通话",
            ["sub.feature_reports"] = "无限 PDF 报告",
            ["sub.feature_replays"] = "完整回放历史",
            ["sub.feature_support"] = "优先支持",
            ["sub.loading"] = "正在加载方案…",
            ["sub.subscribe"] = "订阅",
            ["sub.restore"] = "恢复购买",
            ["sub.restoring"] = "恢复中…",
            ["sub.restored_yes"] = "订阅已恢复！",
            ["sub.restored_no"] = "未找到有效订阅。",
            ["sub.purchasing"] = "处理中…",
            ["sub.purchase_ok"] = "欢迎使用 Sandtray 专业版！",
            ["sub.purchase_err"] = "购买失败：{0}",
            ["sub.terms"] = "订阅将自动续费，除非在续期前24小时取消。",
            ["sub.privacy"] = "隐私政策",
            ["sub.terms_link"] = "使用条款",
            ["sub.best_value"] = "最超值",
            ["sub.save_percent"] = "省 {0}%",
            ["sub.locked_ai"] = "AI 辅助反思是专业版功能。订阅后解锁。",
            ["sub.locked_host"] = "请先登录再托管会话。免费账户可托管3次。",
            ["sub.free_ai_limit"] = "您本月的3次免费AI辅助反思已用完。升级VIP即可无限使用。",
            ["sub.free_pdf_limit"] = "您本月的3次免费PDF导出已用完。升级VIP即可无限导出。",
            ["sub.free_host_limit"] = "您的3次免费托管会话已用完。升级VIP即可无限托管。",
            ["sub.locked_replay"] = "免费账户可播放最新回放。升级VIP即可解锁所有较早的回放。",
            ["sub.period_month"] = "/ 月",
            ["sub.period_year"] = "/ 年",
            ["sub.period_week"] = "/ 周",
            ["sub.period_once"] = "一次性",
            ["sub.no_plans"] = "暂无可用方案。",
            ["sub.mobile_only"] = "订阅仅支持 iOS 与 Android。\n请在手机 App 中完成订阅。",
            ["sub.ok"] = "好的",

            // Brush
            ["brush.radius"] = "半径",
            ["brush.strength"] = "力度",
            ["brush.radius_val"] = "半径:{0:F1}",
            ["brush.strength_val"] = "力度:{0:F1}",

            // Catalog
            ["catalog.title"] = "物品目录",
            ["button.catalog"] = "目录",

            // Status
            ["status.ready"] = "就绪",
            ["status.hint"] = "就绪 - 右键旋转，滚轮缩放，中键平移",
            ["status.selected"] = "已选择：{0}",
            ["status.selected_many"] = "已选择 {0} 个物体 · 拖动任意选中物体可整体移动",
            ["selection.count"] = "已选 {0} 个",
            ["selection.hint"] = "拖动空白沙面框选 · Shift+单击添加或移除",
            ["status.saved"] = "已保存：{0}",
            ["status.autosaved_now"] = "刚刚已自动保存",
            ["status.autosaved_ago"] = "{0}前已自动保存",
            ["status.will_save_in"] = "将在{0}后保存",
            ["status.one_second"] = "{0}秒",
            ["status.seconds"] = "{0}秒",
            ["status.one_minute"] = "{0}分钟",
            ["status.minutes"] = "{0}分钟",
            ["save.title"] = "沙盘保存",
            ["save.local"] = "已保存到此设备 · 自动保存已开启",
            ["quota.pending"] = "等待检查额度",
            ["quota.confirmed"] = "额度已确认",
            ["quota.full"] = "额度已满 · 可继续本地工作",
            ["quota.signin"] = "请登录检查额度 · 可继续本地工作",
            ["quota.offline"] = "暂时无法检查额度 · 将重试",
            ["quota.recovery"] = "额度需要检查 · 本地文件已保留",
            ["quota.none"] = "无需登记本地额度",
            ["quota.legacy"] = "现有本地沙盘",
            ["quota.retry"] = "点击重试额度检查",
            ["backup.none"] = "尚未备份到云端",
            ["backup.unknown"] = "云端备份状态未知",
            ["backup.uploading"] = "正在上传备份…",
            ["backup.saved"] = "已保存版本已备份",
            ["backup.changed"] = "已保存的更改尚未备份",
            ["backup.failed"] = "备份未完成 · 本地文件已保留",
            ["social.google"] = "使用 Google 登录",
            ["social.apple"] = "使用 Apple 登录",
            ["social.continue_google"] = "使用 Google 继续",
            ["social.continue_apple"] = "使用 Apple 继续",
            ["social.open"] = "在浏览器中登录",
            ["social.preparing"] = "正在准备登录…",
            ["social.waiting"] = "请在浏览器中继续。如果未自动打开，请点击下方按钮。",
            ["social.unavailable"] = "第三方登录尚未配置或暂时不可用。仍可使用邮箱登录。",
            ["social.existing"] = "此邮箱已有账号。请使用原有方式登录；尚未启用自动关联账号。",
            ["social.expired"] = "登录已过期，请重试。",
            ["social.cancelled"] = "登录已取消，可以重试。",
            ["social.failed"] = "无法完成登录，请重试。",
            ["save.automatic"] = "自动保存已开启 · 每30秒保存一次",
            ["save.host_managed"] = "由主持人管理保存 · 此设备无本地副本",
            ["save.inactive"] = "自动保存未启用",
            ["save.saved"] = "沙盘更改已保存到此设备",
            ["save.recovered"] = "已恢复此沙盘的上一份保存副本",
            ["save.failed"] = "无法保存。请保持沙盘打开，检查可用存储空间后重试。",
            ["save.load_failed"] = "无法打开此沙盘。已保留原有保存文件。",
            ["save.create_failed"] = "无法保存新沙盘。请重试。如果问题持续，请在设置中检查本地保存恢复。",
            ["status.loaded"] = "已加载：{0}",
            ["status.object"] = "物体",

            // Action panel fallbacks
            ["action.vertical"] = "\u2195",
            ["action.rotate"] = "\u21BB",
            ["action.resize"] = "\u2922",
            ["action.duplicate"] = "复制",
            ["action.delete"] = "\u2716",

            // Analysis
            ["analysis.title"] = "AI 辅助反思",
            ["analysis.ask"] = "生成 AI 反思",
            ["analysis.loading"] = "正在准备反思…请稍候…",
            ["analysis.login_required"] = "创建免费账户或登录后即可使用AI辅助反思。",
            ["analysis.disclaimer"] = "AI辅助反思并非诊断或临床结论。下方将客观观察与可选假设分开呈现；个人意义只能由创作者本人确认。",
            ["analysis.error.capture"] = "无法捕获会话数据。",
            ["analysis.error.manager"] = "场景中未找到 AIAnalysisManager。",
            ["analysis.error"] = "错误：{0}",
            ["analysis.save"] = "保存",
            ["analysis.saved"] = "已保存",
            ["analysis.export_pdf"] = "导出PDF",
            ["analysis.save_not_logged_in"] = "未登录，无法保存",
            ["analysis.saving"] = "正在保存到云端…",
            ["analysis.save_done"] = "已保存到云端",
            ["analysis.auto_saved"] = "已自动保存 · 云端备份已排队",
            ["analysis.auto_save_button"] = "已自动保存",
            ["analysis.save_fail"] = "保存失败：{0}",
            ["analysis.pdf_login_required"] = "导出PDF需要登录",
            ["analysis.wait_save"] = "请等待保存完成…",
            ["analysis.pdf_generating"] = "正在生成PDF…",
            ["analysis.pdf_saved"] = "PDF已保存：{0}",
            ["analysis.pdf_fail"] = "PDF生成失败：{0}",

            // Walk mode
            ["walk.exit"] = "退出行走",

            // Main menu
            ["menu.title"] = "沙盘游戏",
            ["menu.subtitle"] = "治疗工作空间",
            ["menu.welcome"] = "欢迎回来，{0}",
            ["menu.welcome_guest"] = "欢迎",
            ["menu.welcome_sub"] = "在沙盘世界中创作、探索与反思。",
            ["menu.workspace"] = "你的工作空间",
            ["menu.workspace_heading"] = "一个创作与反思的空间",
            ["menu.workspace_sub"] = "新建沙盘，或从上次离开的地方继续。",
            ["menu.continue_playing"] = "我的沙盘",
            ["menu.view_all"] = "查看全部  >",
            ["menu.nav_home"] = "首页",
            ["menu.nav_boards"] = "我的沙盘",
            ["menu.my_boards_sub"] = "{0} 个沙盘 · 用于创作与反思的空间。",
            ["menu.my_boards_open"] = "打开",
            ["menu.search_boards"] = "搜索沙盘",
            ["menu.filter_all"] = "全部沙盘",
            ["menu.filter_client"] = "客户沙盘",
            ["menu.sort_updated"] = "最近更新",
            ["menu.sort_name"] = "名称 A–Z",
            ["menu.sort_oldest"] = "最早更新",
            ["menu.table_board"] = "沙盘",
            ["menu.table_client"] = "客户",
            ["menu.table_updated"] = "最近更新",
            ["menu.table_actions"] = "操作",
            ["menu.range"] = "显示第 {0}–{1} 个，共 {2} 个沙盘",
            ["menu.range_empty"] = "显示 0 个沙盘",
            ["menu.nav_multiplayer"] = "多人协作",
            ["menu.nav_replays"] = "回放",
            ["menu.nav_ai"] = "AI 辅助反思",
            ["menu.nav_objects"] = "物件",
            ["menu.nav_settings"] = "设置",
            ["menu.cta_new_desc"] = "创建一个新的沙盘世界。",
            ["menu.cta_host_desc"] = "创建并邀请他人加入。",
            ["menu.cta_join_desc"] = "加入好友正在进行的会话。",
            ["menu.tile_replays"] = "回放",
            ["menu.tile_replays_desc"] = "回看并反思过往会话。",
            ["menu.tile_ai"] = "AI 辅助反思",
            ["menu.tile_ai_desc"] = "探索客观观察、可选可能性与开放式问题。",
            ["menu.tile_objects"] = "物件库",
            ["menu.tile_objects_desc"] = "解锁全部物件，构建你的世界。",
            ["menu.tile_multiplayer"] = "多人协作",
            ["menu.tile_multiplayer_desc"] = "创建或加入实时会话。",
            ["menu.new_board"] = "新沙盘",
            ["menu.host_online"] = "在线主持",
            ["menu.join_session"] = "加入会话",
            ["menu.saved_boards"] = "已保存的沙盘",
            ["menu.empty"] = "从空白沙盘开始，或使用房间码加入实时会话。",
            ["menu.empty_title"] = "创建你的第一个沙盘",
            ["menu.empty_action"] = "新建沙盘",
            ["menu.empty_join"] = "用房间码加入",
            ["menu.no_results_title"] = "没有符合筛选条件的沙盘",
            ["menu.no_results"] = "请尝试其他搜索内容，或显示全部沙盘。",
            ["menu.clear_filters"] = "清除筛选",
            ["menu.account"] = "账户",
            ["menu.replays"] = "回放",
            ["replays.title"] = "会话回放",
            ["replays.empty"] = "还没有录制的会话。",
            ["replays.duration"] = "{0}秒，{1}条事件",
            ["replays.play"] = "播放",
            ["replays.vip_locked"] = "VIP",
            ["replays.upgrade"] = "升级",
            ["replays.delete"] = "删除",
            ["replays.close"] = "关闭",
            ["replays.confirm_delete"] = "确认删除此回放？",
            ["replays.read_only"] = "只读回放",
            ["replays.stop"] = "停止",
            ["replays.quit"] = "退出",
            ["replays.pause"] = "暂停",
            ["replays.resume"] = "播放",
            ["replays.finished"] = "回放结束",
            ["replays.replay_again"] = "再看一遍",
            ["replays.back_list"] = "返回列表",
            ["replays.free_note"] = "免费版仅可播放最新回放。升级即可解锁全部历史。",
            ["replays.storage_note"] = "回放保存在本机。可删除旧回放以释放空间。",
            ["replays.latest_badge"] = "最新",
            ["replays.reset_view"] = "重置视角",
            ["replays.export_video"] = "导出",
            ["replays.exporting"] = "正在导出视频… {0}%",
            ["replays.export_done"] = "视频已可分享",
            ["replays.export_fail"] = "导出失败：{0}",
            ["replays.export_too_long"] = "回放过长，无法导出（最长5分钟）。",

            // Login / Account
            ["login.title"] = "登录",
            ["login.email"] = "邮箱",
            ["login.welcome_back"] = "欢迎回来",
            ["login.create_heading"] = "创建账户",
            ["login.email_address"] = "邮箱地址",
            ["login.email_placeholder"] = "you@example.com",
            ["login.password_placeholder"] = "输入密码",
            ["login.name_placeholder"] = "输入您的姓名",
            ["login.or"] = "或",
            ["login.have_account"] = "已有账户？",
            ["login.create_account"] = "创建账户",
            ["login.forgot_password"] = "忘记密码？",
            ["login.password"] = "密码",
            ["login.sign_in"] = "登录",
            ["login.register"] = "创建账户",
            ["login.signing_in"] = "登录中...",
            ["login.registering"] = "创建中...",
            ["login.success"] = "欢迎，{0}",
            ["login.error"] = "错误：{0}",
            ["login.logged_in_as"] = "已登录：{0}",
            ["login.sign_out"] = "退出登录",
            ["login.name"] = "姓名",
            ["login.user_type"] = "账户类型",
            ["login.type_normal"] = "个人",
            ["login.type_psychologist"] = "治疗师",
            ["login.type_organization"] = "机构",

            // Board list
            ["board.open"] = "打开",
            ["board.rename"] = "重命名",
            ["board.reports"] = "报告",
            ["board.delete"] = "删除",
            ["board.loading"] = "正在打开沙盘…",
            ["board.loading_new"] = "正在准备沙盘…",
            ["board.loading_catalog"] = "加载图鉴…",
            ["board.loading_prepare"] = "布置沙盘…",
            ["board.loading_restore"] = "恢复沙盘…",
            ["board.loading_objects"] = "放置物件…",
            ["board.loading_ready"] = "即将完成…",

            // Reports panel
            ["reports.title"] = "报告：{0}",
            ["reports.empty"] = "暂无AI反思报告。\n打开此沙盘并生成一份AI辅助反思。",
            ["reports.view"] = "查看",
            ["reports.delete"] = "删除",
            ["reports.pdf"] = "\uD83D\uDCC4 PDF",
            ["reports.detail_title"] = "报告 — {0}",
            ["reports.pdf_login"] = "请登录以导出PDF",
            ["reports.pdf_uploading"] = "上传中…",
            ["reports.pdf_downloading"] = "生成PDF中…",
            ["reports.pdf_saved"] = "PDF已保存!",
            ["reports.pdf_error"] = "PDF错误：{0}",

            // Dialogs
            ["dialog.new_board"] = "新沙盘",
            ["dialog.rename"] = "重命名沙盘",
            ["dialog.ok"] = "确定",
            ["dialog.cancel"] = "取消",
            ["exit.title"] = "退出沙盘？",
            ["exit.confirm"] = "确定要退出当前沙盘并返回主菜单吗？",

            // Size dialog
            ["size.title"] = "选择沙盘大小",
            ["size.standard"] = "标准（正方形）",
            ["size.standard_desc"] = "10 × 10",
            ["size.medium"] = "中等（宽型）",
            ["size.medium_desc"] = "10 × 13",
            ["size.custom"] = "自定义",
            ["size.width"] = "宽：",
            ["size.depth"] = "深：",

            // Host panel
            ["host.title"] = "在线主持会话",
            ["host.info"] = "选择主持模式，然后打开一个沙盘。\n进入沙盘后将创建房间。",
            ["host.cloud"] = "\u2601  云端会话（房间码 - 随处可用）",
            ["host.lan"] = "\u26A1  局域网会话（同一Wi-Fi - IP：{0}）",
            ["host.cancel"] = "取消",

            // Join panel
            ["join.title"] = "加入会话",
            ["join.role_label"] = "加入身份：",
            ["join.observer"] = "观察者",
            ["join.therapist"] = "治疗师",
            ["join.patient"] = "来访者",
            ["host.therapist_mode"] = "治疗师模式",
            ["host.therapist_mode_desc"] = "点击切换。参与者先旁观，由您在管理中批准编辑。",
            ["host.client_edits"] = "来访者编辑 · 我主持并观察",
            ["host.client_edits_desc"] = "首位加入的来访者将自动获得编辑权限。您可在管理中更改。",
            ["net.connection_error_title"] = "会话连接失败",
            ["net.dismiss"] = "关闭",
            ["clients.confirm_move"] = "确认移至 {0}",
            ["reports.review_title"] = "导出前审阅",
            ["reports.edit"] = "编辑报告",
            ["reports.revisions"] = "历史版本",
            ["reports.revisions_notice"] = "原文按最新优先排列。日期为文本替换时间。此本地历史不是经过验证的审计记录。",
            ["reports.revisions_empty"] = "暂无历史版本。",
            ["reports.edit_notice"] = "更改保存在本地并保留原文。编辑后需重新导出 PDF。AI 文本不是诊断。",
            ["reports.edit_stale"] = "报告或账户已更改。请关闭并重新打开报告后再编辑。",
            ["reports.review_notice"] = "请检查报告的准确性及敏感信息。AI 文本不是诊断。继续将把报告发送到服务器以导出 PDF。",
            ["reports.review_confirm"] = "已审阅 · 导出 PDF",
            ["clients.history_no_matches"] = "没有匹配的沙盘。清空搜索以查看全部记录。",
            ["clients.history"] = "分配历史",
            ["clients.history_unassigned"] = "未分配",
            ["clients.history_missing"] = "来访者档案缺失（{0}）",
            ["clients.history_local"] = "本设备历史，并非经验证的审计日志。姓名来自当前档案。",
            ["clients.history_change"] = "原来：{0}\n现在：{1}",
            ["clients.history_unknown_date"] = "日期未知",
            ["clients.history_empty"] = "暂无分配变更记录。",
            ["clients.search_tables"] = "按名称搜索沙盘…",
            ["clients.recovered"] = "已从本地备份恢复客户记录。最近的更改可能缺失，请检查。",
            ["clients.search_reports"] = "搜索沙盘名称或报告内容…",
            ["session.paused"] = "编辑已暂停",
            ["session.paused_name"] = "已暂停：{0}",
            ["session.waiting"] = "等待编辑者",
            ["session.editing_name"] = "正在编辑：{0}",
            ["session.you_edit"] = "你可编辑",
            ["session.observing"] = "观察中",
            ["session.manage"] = "管理",
            ["session.resume"] = "恢复编辑",
            ["session.pause"] = "暂停编辑",
            ["session.take_control"] = "由我编辑",
            ["session.editing"] = "编辑中",
            ["session.approve"] = "批准编辑",
            ["session.give_control"] = "授予编辑权",
            ["session.decline"] = "拒绝编辑请求",
            ["session.remove"] = "移出会话",
            ["session.confirm_remove"] = "确认移出",
            ["session.waiting_people"] = "等待参与者…",
            ["catalog.edit_permission_title"] = "需要编辑权限",
            ["catalog.edit_permission_required"] = "您没有编辑此沙盘的权限。请让主持人授予编辑权限。",
            ["catalog.host_edit_permission_required"] = "您当前处于观察状态。请打开“管理”并选择“由我编辑”，然后使用物件目录。",
            ["session.loading_title"] = "正在加载会话",
            ["session.loading_receiving"] = "正在接收会话… 0%",
            ["session.loading_objects"] = "正在加载物件… {0}/{1}（{2}%）",
            ["session.loading_success"] = "会话已就绪 · 100%",
            ["session.loading_failed_title"] = "无法加载会话",
            ["session.loading_failed"] = "部分会话物件无法加载。",
            ["session.loading_disconnected"] = "会话加载完成前连接已断开。",
            ["session.loading_return"] = "返回主页",
            ["session.removed"] = "主持人已将你移出此会话。点击关闭。",
            ["net.update_required"] = "应用与会话服务器版本不兼容。请更新应用；若已是最新版，请联系支持更新服务器。点击关闭。",
            ["host.i_edit"] = "我编辑 · 其他人旁观",
            ["net.patient_active"] = "来访者已连接",
            ["therapist.patient_acting"] = "来访者正在操作…",
            ["therapist.patient_painting"] = "来访者正在上色…",
            ["therapist.patient_placing"] = "来访者放置了一个物件",
            ["join.cloud_label"] = "通过房间码加入",
            ["join.placeholder_code"] = "ABC123",
            ["join.scan_qr"] = "扫码",
            ["join.join_room"] = "加入房间",
            ["join.invalid_code"] = "请输入房间码（4-6个字母）",
            ["join.joining"] = "加入中…",
            ["join.room_not_found"] = "未找到房间或连接失败",
            ["join.or"] = "或",
            ["join.lan_label"] = "\u26A1  通过IP地址加入（同一Wi-Fi）",
            ["join.placeholder_ip"] = "192.168.1.",
            ["join.connect"] = "连接",
            ["join.missing_ip"] = "请输入IP地址",
            ["join.connecting"] = "连接中…",
            ["join.connection_failed"] = "连接失败",
            ["join.cancel"] = "取消",

            // Network
            ["net.room"] = "房间：{0}",
            ["net.connecting"] = "连接中…",
            ["net.spectating"] = "观看中",
            ["net.viewers"] = "{0} 位观众",
            ["net.viewers_s"] = "",

            // Reconnect
            ["reconnect.return"] = "返回菜单",
            ["reconnect.message"] = "连接中断\n正在重连… ({0}/10)",

            // Settings
            ["settings.title"] = "设置",
            ["clients.title"] = "来访者",
            ["clients.new"] = "+ 新建来访者",
            ["clients.local_note"] = "来访者资料、沙盘与报告保存在本设备，暂不支持云同步。",
            ["clients.local_archived"] = "包含已归档来访者 · 保存在本设备，未同步到云端。",
            ["clients.search"] = "搜索姓名或来访者编号…",
            ["clients.archived_toggle"] = "显示 / 隐藏已归档",
            ["clients.archived"] = "已归档",
            ["clients.empty"] = "暂无匹配的来访者。新建来访者后即可整理沙盘。",
            ["clients.unassigned"] = "未分配的沙盘",
            ["clients.unassigned_help"] = "现有沙盘保留在这里，直到你将其移入来访者档案。移动沙盘会保留全部报告。",
            ["clients.counts"] = "{0} 个沙盘 · {1} 份报告",
            ["clients.report_count"] = "{0} 份报告",
            ["clients.edit"] = "编辑资料",
            ["clients.new_table"] = "+ 新建沙盘",
            ["clients.archive"] = "归档来访者",
            ["clients.restore"] = "恢复来访者",
            ["clients.tables"] = "沙盘",
            ["clients.reports"] = "报告",
            ["clients.view"] = "查看",
            ["clients.open"] = "打开",
            ["clients.move"] = "移动",
            ["clients.move_title"] = "移至来访者",
            ["clients.no_tables"] = "暂无沙盘。可以为来访者新建沙盘，或从未分配的沙盘、我的沙盘中移入。",
            ["clients.no_reports"] = "暂无报告。此来访者沙盘中保存的报告将在这里显示。",
            ["clients.name"] = "姓名或化名 *",
            ["clients.reference"] = "来访者编号",
            ["clients.dob"] = "出生日期",
            ["clients.choose_date"] = "选择日期…",
            ["clients.no_date"] = "尚未选择日期 · 选填",
            ["clients.clear_date"] = "清除",
            ["clients.done"] = "完成",
            ["clients.select"] = "选择",
            ["clients.choose_photo"] = "选择照片",
            ["clients.remove_photo"] = "移除",
            ["clients.photo_hint"] = "选填头像 · 预览采用居中裁剪，仅保存在此设备。",
            ["clients.photo_error"] = "无法打开照片。请检查照片权限，或选择小于20 MB的JPG/PNG图片。",
            ["clients.phone"] = "电话",
            ["clients.email"] = "邮箱",
            ["clients.optional"] = "仅姓名或化名为必填项。来访者不需要注册应用账号。",
            ["clients.notes"] = "备注",
            ["clients.save"] = "保存资料",
            ["clients.invalid_name"] = "请输入姓名或化名（最多 100 字符）。",
            ["clients.rename_error"] = "无法重命名此沙盘。请选择一个尚未使用的名称。",
            ["clients.invalid_dob"] = "请输入有效出生日期：YYYY-MM-DD，不能晚于今天。",
            ["clients.invalid_account"] = "请从搜索或好友中选择有效账号。",
            ["clients.account_locked"] = "此来访者已关联账号，不能在此替换已保存的身份。",
            ["clients.duplicate_account"] = "此账号已关联其他来访者（包括已归档档案），请打开现有档案。",
            ["clients.duplicate_reference"] = "该来访者编号已被使用，请更换编号或留空。",
            ["clients.storage_error"] = "无法读取或保存本地档案。请检查设备存储后重试。",
            ["settings.close"] = "\u00D7",
            ["settings.sand_color"] = "沙子颜色",
            ["settings.box_outer"] = "盒子外层",
            ["settings.box_inner"] = "盒子内层",
            ["settings.floor"] = "地板",
            ["settings.allow_objects_in_air"] = "允许物体悬空",
            ["settings.restore"] = "恢复默认",
            ["settings.pick"] = "选择",
            ["shortcuts.title"] = "键盘快捷键",
            ["shortcuts.hint"] = "点击按键组合即可修改，设置保存在此设备。按住Shift可微调物体。",
            ["shortcuts.search"] = "搜索操作或按键…",
            ["shortcuts.default"] = "默认",
            ["shortcuts.custom"] = "已自定义",
            ["shortcuts.reset"] = "重置",
            ["shortcuts.reset_all"] = "全部重置",
            ["shortcuts.reset_confirm"] = "恢复全部默认快捷键？自定义按键设置将被移除。",
            ["shortcuts.press"] = "按下新的按键组合，然后点击保存。Esc取消。需要实体键盘。",
            ["shortcuts.fine"] = "此操作的Shift键保留用于微调。",
            ["shortcuts.save"] = "保存",
            ["shortcuts.saved"] = "快捷键已保存在此设备。",
            ["shortcuts.unassign"] = "取消绑定",
            ["shortcuts.reserved"] = "此按键保留用于导航、相机或系统操作，请选择其他组合。",
            ["shortcuts.conflict"] = "已用于“{0}”。请先修改或取消该操作的绑定。",
            ["shortcuts.save_error"] = "无法保存快捷键，请重试。",
            ["shortcuts.empty"] = "没有匹配的快捷键。",
            ["shortcuts.action.Raise"] = "升高物体",
            ["shortcuts.action.Lower"] = "降低物体",
            ["shortcuts.action.RotateLeft"] = "向左旋转",
            ["shortcuts.action.RotateRight"] = "向右旋转",
            ["shortcuts.action.Enlarge"] = "放大物体",
            ["shortcuts.action.Shrink"] = "缩小物体",
            ["shortcuts.action.Duplicate"] = "复制物体到旁边",
            ["shortcuts.action.Delete"] = "删除物体",
            ["shortcuts.action.Copy"] = "拷贝物体",
            ["shortcuts.action.Paste"] = "粘贴物体",
            ["shortcuts.action.Undo"] = "撤销",
            ["shortcuts.action.Redo"] = "重做",
            ["settings.language"] = "语言",
            ["settings.theme"] = "外观",
            ["settings.theme_light"] = "浅色",
            ["settings.theme_dark"] = "深色",
            ["board.client_label"] = "来访者：{0}",
            ["board.client_linked"] = "已关联来访者",
            ["settings.description"] = "按照你的习惯，自定义 Sandtray。",
            ["settings.subscription"] = "订阅",
            ["settings.view_plans"] = "查看方案 ›",
            ["settings.configure"] = "自定义 ›",
            ["settings.view"] = "查看 ›",
            ["settings.sign_in"] = "登录",
            ["settings.managed"] = "受管理账户",
            ["settings.off"] = "关闭",
            ["settings.on"] = "开启",
            ["settings.reset"] = "重置",
            ["settings.custom_color"] = "自定义颜色…",
            ["credits.title"] = "资源署名",
            ["credits.subtitle"] = "感谢为三维物体提供作品的创作者",
            ["credits.body"] = "内置三维模型包含 Poly by Google 的作品，来源于 Poly Pizza（poly.pizza）。\n采用知识共享署名 3.0 未本地化版本许可（CC BY 3.0）。",
            ["credits.changes"] = "适配说明：模型导入 Unity 并调整尺寸以用于 Sandtray；材质及渲染效果可能与原作不同。",
            ["credits.disclaimer"] = "此署名不代表 Google 或 Poly Pizza 对 Sandtray 的赞助或认可，也不涵盖用户上传的物体。",
            ["credits.creator"] = "创作者主页",
            ["credits.source"] = "Poly Pizza",
            ["credits.models"] = "模型署名",
            ["account.type_title"] = "账户类型",
            ["account.type_hint"] = "切换 Sandtray 的使用方式。沙盘、来访者记录和报告都会保留，不会更改订阅或验证专业资质。",
            ["account.normal"] = "个人",
            ["account.personal"] = "个人",
            ["account.therapist"] = "治疗师",
            ["account.organization"] = "机构",
            ["organization.nav"] = "机构",
            ["account.current"] = "当前",
            ["account.sign_in"] = "请通过上方的账户按钮登录后更改账户类型。",
            ["account.managed"] = "此账户类型由管理员管理。",
            ["account.saving"] = "正在保存账户类型…",
            ["records.capacity_pending"] = "正在保存报告，等待容量确认…",
            ["account.saved"] = "账户类型已保存。",
            ["account.failed"] = "保存失败，请检查网络连接后重试。",
            ["credits.license"] = "CC BY 3.0",

            // Color picker
            ["colorpicker.title"] = "选择颜色",
            ["colorpicker.done"] = "完成",

            // QR scanner
            ["qr.title"] = "扫描二维码",
            ["qr.instruction"] = "将摄像头对准房间二维码",
            ["qr.cancel"] = "取消",
            ["qr.requesting"] = "正在请求摄像头权限…",
            ["qr.waiting"] = "等待摄像头…",
            ["qr.scanning"] = "扫描中…",
            ["qr.found"] = "已找到：{0}",
            ["qr.tap_close"] = "点击任意位置关闭",

            // HUD
            ["hud.radius"] = "半径：{0:F1}",
            ["hud.strength"] = "力度：{0:F1}",
            ["hud.select"] = "选择",
            ["hud.raise_sand"] = "堆沙",
            ["hud.dig_sand"] = "挖沙",
            ["hud.smooth_sand"] = "平滑沙面",
            ["hud.flatten_sand"] = "压平沙面",
            ["hud.place_object"] = "放置物体",
            ["hud.move_object"] = "移动物体",
            ["hud.rotate_object"] = "旋转物体",
            ["hud.scale_object"] = "缩放物体",
            ["hud.none"] = "无",
            ["hud.saved"] = "会话已保存！",
            ["hud.loaded"] = "会话已加载！",
            ["hud.screenshot"] = "截图已保存！",
            ["hud.analysis"] = "已请求分析…",

            // Agora voice / video
            ["agora.mic_on"] = "开麦",
            ["agora.mic_off"] = "静音",
            ["agora.cam_on"] = "开摄像头",
            ["agora.cam_off"] = "关摄像头",
            ["agora.show"] = "显示",
            ["agora.hide"] = "隐藏",
            ["agora.leave"] = "挂断",
            ["agora.connecting"] = "连接音频中…",
            ["agora.comm_title"] = "语音视频",
            ["agora.you"] = "我",

            // Object categories
            ["cat.Animals"] = "动物",
            ["cat.People"] = "人物",
            ["cat.Buildings"] = "建筑",
            ["cat.Nature"] = "自然",
            ["cat.Vehicles"] = "交通工具",
            ["cat.Abstract"] = "抽象",
        };
    }
}
