using System.Collections.Generic;
namespace Sandplay.Core
{
    public static partial class Localization
    {
        private static readonly Dictionary<string, string[]> AccessText = new Dictionary<string, string[]>
        {
            ["access.credit_source"] = new[] { "Granted credits: {0}", "额外额度：{0}" },
            ["access.credit_detail"] = new[] { "Available: {0} · Pending: {1}\nUsed: {2} of {3}\nExpires: {4} · {5}", "可用：{0} · 待完成：{1}\n已用：{2} / {3}\n到期：{4} · {5}" },
            ["access.credit_restricted"] = new[] { "Use is restricted", "当前限制使用" },
            ["access.credit_active"] = new[] { "Active", "生效中" },
            ["access.credit_inactive"] = new[] { "Scheduled, expired or revoked", "未生效、已到期或已撤销" },
            ["access.extra_credits"] = new[] { "+{0} available non-renewing credits", "+{0} 可用额外额度（不自动重置）" },
            ["access.host_ending"] = new[] { "Hosting access is ending within {0} minutes under the current policy. Save your table now.", "按当前权限，主持资格将在 {0} 分钟内结束。请立即保存沙盘。" },
            ["access.host_deadline"] = new[] { "Session ending in {0}s · save a local copy", "会话将在 {0} 秒后结束 · 请保存本地副本" },
            ["access.host_connection"] = new[] { "Connection interrupted · reconnecting…", "连接中断 · 正在重新连接…" },
            ["access.host_recovery"] = new[] { "Hosting disconnected. Save your table on this device before leaving.", "主持连接已断开。离开前请在此设备保存沙盘。" },
            ["access.host_low"] = new[] { "Monthly hosting time is low: {0} minutes at last check. Save your table.", "每月主持时间即将用尽：上次检查剩余 {0} 分钟。请保存沙盘。" },
            ["access.host_unknown"] = new[] { "Hosting time could not be refreshed. Save your table while the connection is checked.", "无法刷新主持时间。检查连接期间请保存沙盘。" },
            ["access.save_now"] = new[] { "Save", "保存" },
            ["access.saved"] = new[] { "Table saved on this device.", "沙盘已保存在此设备。" },
            ["access.save_failed"] = new[] { "Table could not be saved. Try again before leaving.", "无法保存沙盘。离开前请重试。" },
            ["cloud.manage"] = new[] { "Manage backup", "管理备份" },
            ["cloud.trash"] = new[] { "Move to trash", "移至回收站" },
            ["cloud.purge"] = new[] { "Delete permanently", "永久删除" },
            ["cloud.untrash"] = new[] { "Restore from trash", "从回收站恢复" },
            ["cloud.trash_notice"] = new[] { "Move this cloud backup to trash? Shared access will be revoked. History still uses storage; local tables stay unchanged.", "将此云端备份移至回收站？分享权限将撤销。历史仍占用存储；本地沙盘不变。" },
            ["cloud.purge_notice"] = new[] { "Permanently delete all cloud versions of this backup? This cannot be undone. Local copies remain. You can instead restore it from trash.", "永久删除此备份的所有云端版本？此操作无法撤销。本地副本保留。也可选择从回收站恢复。" },
            ["ownership.active"] = new[] { "Account-isolated local storage is enabled on this device.", "此设备已启用本地账号隔离存储。" },
            ["ownership.title"] = new[] { "Prepare local ownership", "准备本地数据归属" },
            ["cloud.title"] = new[] { "Cloud backups", "云端备份" },
            ["cloud.backup"] = new[] { "Back up a local table", "备份本地沙盘" },
            ["cloud.refresh"] = new[] { "Cloud library", "云端资料库" },
            ["cloud.next"] = new[] { "Next page", "下一页" },
            ["cloud.review"] = new[] { "Review upload", "确认上传内容" },
            ["cloud.confirm"] = new[] { "Upload private backup", "上传私密备份" },
            ["cloud.restore_copy"] = new[] { "Restore a copy", "恢复为副本" },
            ["cloud.library_notice"] = new[] { "Private backups. Restoring creates a new local copy.", "私密备份。恢复时将创建新的本地副本。" },
            ["cloud.select_notice"] = new[] { "Select a saved table to review. Nothing uploads until you confirm.", "选择已保存的沙盘以查看上传内容。确认前不会上传。" },
            ["cloud.backup_notice"] = new[] { "Upload this saved copy to account {0}? Confirm this account is allowed to keep the table and its notes/reports. This does not share it with others.", "将此已保存副本上传至账号 {0}？请确认该账号有权保存沙盘及其笔记与报告。此操作不会分享给他人。" },
            ["cloud.backup_scope"] = new[] { "Includes scene data, private notes and {0} reports. Object model files and client profiles are not included.", "包含场景数据、私密笔记及 {0} 份报告。不包含物件模型文件及来访者档案。" },
            ["cloud.restore_notice"] = new[] { "Restore your latest backup as a new local table? Existing tables stay intact. Local client associations are cleared; model files must already be available.", "将最新备份恢复为新的本地沙盘？现有沙盘不变。本地来访者关联将清除；模型文件需另行提供。" },
            ["cloud.uploading"] = new[] { "Uploading… wait for server confirmation.", "正在上传…请等待服务器确认。" },
            ["cloud.saved"] = new[] { "Private cloud backup confirmed. Your local table is unchanged.", "私密云端备份已确认。本地沙盘未改变。" },
            ["cloud.restored"] = new[] { "Restored on this device: {0}", "已恢复到此设备：{0}" },
            ["access.cloud.backup"] = new[] { "Cloud backup", "云端备份" },
            ["access.cloud.share"] = new[] { "Share cloud tables", "分享云端沙盘" },
            ["access.cloud.storage_bytes"] = new[] { "Cloud storage bytes", "云存储字节" },
            ["access.cloud.records.capacity"] = new[] { "Cloud backup records", "云端备份记录" },
            ["access.title"] = new[] { "Access & usage", "权限与用量" },
            ["access.loading"] = new[] { "Loading your access…", "正在加载权限…" },
            ["access.refresh"] = new[] { "Refresh", "刷新" },
            ["access.signin"] = new[] { "Sign in to view your access and usage.", "登录后查看权限与用量。" },
            ["access.error"] = new[] { "Access could not be loaded. Check your connection and refresh.", "无法加载权限。请检查网络后刷新。" },
            ["access.preview"] = new[] { "Configured access preview. These allowances are not active yet.", "已配置的权限预览。这些额度尚未启用。" },
            ["access.partial"] = new[] { "Some limits are active. Usage is shown only where tracking is available.", "部分限制已启用。仅显示已开始统计的用量。" },
            ["access.stale"] = new[] { "This information may have changed. Refresh to check your current access.", "信息可能已变化。请刷新查看当前权限。" },
            ["access.inactive"] = new[] { "This account is inactive.", "此账号已停用。" },
            ["access.baseline"] = new[] { "Standard account access", "标准账号权限" },
            ["access.unknown"] = new[] { "Usage not available", "暂无用量信息" },
            ["access.yes"] = new[] { "Included", "已包含" },
            ["access.no"] = new[] { "Not included", "未包含" },
            ["access.unlimited"] = new[] { "Unlimited", "不限量" },
            ["access.duration"] = new[] { "{0}h {1}m {2}s", "{0}小时 {1}分 {2}秒" },
            ["access.host_balance"] = new[] { "Used: {0}\nReserved: {1}\nAvailable: {2}", "已用：{0}\n预留：{1}\n可用：{2}" },
            ["access.month"] = new[] { "{0} / month", "每月 {0}" },
            ["access.balance"] = new[] { "{0} used · {1} pending · {2} remaining", "已用 {0} · 处理中 {1} · 剩余 {2}" },
            ["access.reset"] = new[] { "Resets {0}", "重置时间 {0}" },
            ["access.source"] = new[] { "{0} · {1}\nUntil {2}", "{0} · {1}\n有效期至 {2}" },
            ["access.manual"] = new[] { "Manual access", "手动授权" },
            ["access.promotion"] = new[] { "Promotional access", "活动授权" },
            ["access.tables.capacity"] = new[] { "Stored tables", "已存沙盘" },
            ["access.objects.builtin.read"] = new[] { "Built-in objects", "内置物件" },
            ["access.reports.capacity"] = new[] { "Stored reports", "已存报告" },
            ["access.reports.share"] = new[] { "Share reports", "分享报告" },
            ["access.reports.receive"] = new[] { "Receive reports", "接收报告" },
            ["access.replays.record"] = new[] { "Record replays", "录制回放" },
            ["access.replays.play"] = new[] { "Watch replays", "观看回放" },
            ["access.sessions.host"] = new[] { "Host sessions", "主持会话" },
            ["access.sessions.join"] = new[] { "Join sessions", "加入会话" },
            ["access.sessions.session_minutes"] = new[] { "Maximum minutes per session", "每次会话分钟上限" },
            ["access.sessions.host_minutes"] = new[] { "Hosting minutes", "主持分钟数" },
            ["access.sessions.participants"] = new[] { "Session participants", "会话参与人数" },
            ["access.ai.analyze"] = new[] { "AI analyses", "AI 分析" },
            ["access.pdf.export"] = new[] { "PDF exports", "PDF 导出" },
            ["access.catalog.custom.capacity"] = new[] { "Custom objects", "自定义物件" },
            ["access.clients.capacity"] = new[] { "Clients", "来访者" },
            ["access.clients.manage"] = new[] { "Manage clients", "管理来访者" },
            ["access.reports.templates"] = new[] { "Report templates", "报告模板" },
        };
        private static bool TryGetAccessTranslation(string key, out string value)
        {
            value = null;
            if (!AccessText.TryGetValue(key, out var text)) return false;
            value = text[Current == Language.Chinese ? 1 : 0];
            return true;
        }
    }
}
